### ISSUE TITLE
Summed term

### ISSUE THREAD

**Issue by freiburgermsu** [himoto/fitting_hilleq#16]
Hello!

I was [reading about the Hill equation](https://link.springer.com/content/pdf/10.1007/s00407-012-0098-5.pdf), and I observed that the reported expression of the Hill equation
![Proper Hill-equation](https://user-images.githubusercontent.com/60083977/152265851-b2ec01d5-3266-4339-8781-42a1fc9eb9f9.JPG)
<img src="https://render.githubusercontent.com/render/math?math=[L_n R] = \frac{[R_0]*[L]^n}{K^n*[L]^n}">
lacks a summed term of `bottom` to the right-hand side that is included in the HillFit expression. Where is the HillFit expression of the Hill equation reported in literature, or are the terms mathematically equivalent?

**Comment by himoto** [comment]
Hi @freiburgermsu!
I obtained the HillFit expression of the Hill equation from this paper https://www.nature.com/articles/npjsba201624#Sec10.
When `bottom`=0 and consider `top` as [R0], we get the same equation.

From your comment, I found that there might be some users who do not want to estimate the `bottom` value from data.
It would be interesting if we introduce an argument, e.g., `fix_bottom`, which can take float or None.
When it is None, `bottom` will be estimated from experimental data, but for example, `bottom`=0.0, `bottom` value is fixed to 0.0. I would be happy if you could give me comments on this function. Do you think we can implement this?

**Comment by freiburgermsu** [comment]
Hello @himoto !

[I just submitted a PR](https://github.com/himoto/hillfit/pull/17).
