### ISSUE TITLE
How to turn off the view_figure

### ISSUE THREAD

**Issue by DongyuZhaoPG** [himoto/fitting_hilleq#19]
it seem that the figure is still showing even that I put view_figure = False

please help

**Comment by himoto** [comment]
Hi @DongyuZhaoPG, thank you for your inquiry.

@freiburgermsu Do you know how to resolve this?

```python
if view_figure:
    self.figure.show()
```
At a glance, code looks OK.

**Comment by freiburgermsu** [comment]
@DongyuZhaoPG I have a few questions:

1. Are you operating in a Jupyter Notebook? I believe that figures render in Notebooks anytime ``pyplot`` is called and defined, irrespective of actually calling ``pyplot.show()``.
2. Do you want to generate a figure at all? We can place the entire construction of the figure in conditional logic, so the figure will simply not be created.

**Comment by DongyuZhaoPG** [comment]
@freiburgermsu , @himoto  thanks for getting back!
yes, I am working in a Jupyter Notebook, thanks for explaining that.
I don't want the figure to be generated, much appreciate if we could make it into a conditional logic! thanks so much!

**Comment by freiburgermsu** [comment]
Hello @DongyuZhaoPG,

I just developed new logic that will optionally not generate the regression figure with an argument. 

@himoto Can you push these edits to PyPI in a new version?

Thank you :)

**Comment by himoto** [comment]
@freiburgermsu I released hillfit 0.1.5, which includes the update #20

**Comment by freiburgermsu** [comment]
@himoto Thank you !
