### ISSUE TITLE
view_figure argument not working in fitting() function

### ISSUE THREAD

**Issue by timbo112711** [himoto/fitting_hilleq#25]
When calling `hf.fitting()` the `view_figure` argument is not working. Either bool, `True` or `False`, displays the figure. I am trying to use this package in a Dash app and just need the `x_fit`, `y_fit`, and `ec50` values for plotting a Plotly line chart.

**Comment by himoto** [comment]
Hello @timbo112711, thank you for your inquiry.
Hi @freiburgermsu, can you please check this?

**Comment by freiburgermsu** [comment]
Hello @timbo112711 !

Some IDEs automatically render figures, despite when the figures are not explicitly called. Try setting `generate_figure=False`, which will prevent the figure from ever being created yet will still yield the contents that you desire.

The forthcoming updates have some additional functionality to help your workflow.

Andrew

**Comment by himoto** [comment]
Hi @timbo112711,
We have updated `master` branch to try to resolve this issue.
To try this out, please install hillfit via:
```
$ pip install git+https://github.com/himoto/hillfit
```

Please do let me know if this works.

**Comment by timbo112711** [comment]
Hi @freiburgermsu !!

That arg worked like a charm. Can't believe I overlooked that one. 

@himoto , Will do thanks!
